package fr.dreamin.dreamapi.core.item.builder;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.bukkit.Material;
import org.jetbrains.annotations.NotNull;

@Getter
@RequiredArgsConstructor
public enum BannerType {

  BLUE_BANNER(Material.BLUE_BANNER),
  BLUE_WALL_BANNER(Material.BLUE_WALL_BANNER),
  LIGHT_BLUE_BANNER(Material.LIGHT_BLUE_BANNER),
  LIGHT_BLUE_WALL_BANNER(Material.LIGHT_BLUE_WALL_BANNER),
  GREEN_BANNER(Material.GREEN_BANNER),
  GREEN_WALL_BANNER(Material.GREEN_WALL_BANNER),
  BLACK_BANNER(Material.BLACK_BANNER),
  BLACK_WALL_BANNER(Material.BLACK_WALL_BANNER),
  BROWN_BANNER(Material.BROWN_BANNER),
  BROWN_WALL_BANNER(Material.BROWN_WALL_BANNER),
  CYAN_BANNER(Material.CYAN_BANNER),
  CYAN_WALL_BANNER(Material.CYAN_WALL_BANNER),
  GRAY_BANNER(Material.GRAY_BANNER),
  GRAY_WALL_BANNER(Material.GRAY_WALL_BANNER),
  LIGHT_GRAY_BANNER(Material.LIGHT_GRAY_BANNER),
  LIGHT_GRAY_WALL_BANNER(Material.LIGHT_GRAY_WALL_BANNER),
  YELLOW_BANNER(Material.YELLOW_BANNER),
  YELLOW_WALL_BANNER(Material.YELLOW_WALL_BANNER),
  MAGENTA_BANNER(Material.MAGENTA_BANNER),
  MAGENTA_WALL_BANNER(Material.MAGENTA_WALL_BANNER),
  ORANGE_BANNER(Material.ORANGE_BANNER),
  ORANGE_WALL_BANNER(Material.ORANGE_WALL_BANNER),
  RED_BANNER(Material.RED_BANNER),
  RED_WALL_BANNER(Material.RED_WALL_BANNER),
  PINK_BANNER(Material.PINK_BANNER),
  PINK_WALL_BANNER(Material.PINK_WALL_BANNER),
  PURPLE_BANNER(Material.PURPLE_BANNER),
  PURPLE_WALL_BANNER(Material.PURPLE_WALL_BANNER),
  WHITE_BANNER(Material.WHITE_BANNER),
  WHITE_WALL_BANNER(Material.WHITE_WALL_BANNER);

  private final @NotNull Material type;

}
